name: stellaris-scraper
channels:
  - conda-forge
dependencies:
  - python=3.11
  - tqdm
  - beautifulsoup4
  - lxml
  - pyyaml
  - pip
  - pydantic
  - pip:
    - cloudscraper
    - fastmcp
    - -e .
